# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc10a5594315b81bacef3abb9f41d480e044449f79afb85b12ddca7ed62713e7512f78a1aa23888565f4ce398810d67218b6ae89d3530b6d47b4db14acea375f

test:
  secret_key_base: bb33776e138e0cc1d80237e57226648e0e505561f7a749454a44dc191df33374c5ca76ece2a9a05581997da7b4e6087a7c5d8a53156e6fb2566e8634ad79854e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
